# Tp03 : Étude de cas Yelp

## Création du Dataset

### Import des librairie

In [2]:
import pandas as pd
from pandas import read_csv, DataFrame
import numpy as np
from utils import create_data_path

### Variable

In [3]:
data_set_path: dict[str, str] = {
    "avis"         : create_data_path("avis.csv"),
    "categories"   : create_data_path("categories.csv"),
    "checkin"      : create_data_path("checkin.csv"),
    "conseils"     : create_data_path("conseils.csv"),
    "horaires"     : create_data_path("horaires.csv"),
    "restaurants"  : create_data_path("restaurants.csv"),
    "services"     : create_data_path("services.csv"),
    "utilisateurs" : create_data_path("utilisateurs.csv")
}

c:\Users\DCS2003\Desktop\1-cegep\5-session05\5-collecte_interpretation\2-travaux_pratique\2-python\420-514-MV-TP03
c:\Users\DCS2003\Desktop\1-cegep\5-session05\5-collecte_interpretation\2-travaux_pratique\2-python\420-514-MV-TP03
c:\Users\DCS2003\Desktop\1-cegep\5-session05\5-collecte_interpretation\2-travaux_pratique\2-python\420-514-MV-TP03
c:\Users\DCS2003\Desktop\1-cegep\5-session05\5-collecte_interpretation\2-travaux_pratique\2-python\420-514-MV-TP03
c:\Users\DCS2003\Desktop\1-cegep\5-session05\5-collecte_interpretation\2-travaux_pratique\2-python\420-514-MV-TP03
c:\Users\DCS2003\Desktop\1-cegep\5-session05\5-collecte_interpretation\2-travaux_pratique\2-python\420-514-MV-TP03
c:\Users\DCS2003\Desktop\1-cegep\5-session05\5-collecte_interpretation\2-travaux_pratique\2-python\420-514-MV-TP03
c:\Users\DCS2003\Desktop\1-cegep\5-session05\5-collecte_interpretation\2-travaux_pratique\2-python\420-514-MV-TP03

### Charger Dataset

In [4]:
df_avis         = read_csv(data_set_path["avis"])
df_categories   = read_csv(data_set_path["categories"])
df_checking     = read_csv(data_set_path["checkin"])
df_conseils     = read_csv(data_set_path["conseils"])
df_horaires     = read_csv(data_set_path["horaires"])
df_restaurants  = read_csv(data_set_path["restaurants"])
df_services     = read_csv(data_set_path["services"])
df_utilisateurs = read_csv(data_set_path["utilisateurs"])

In [ ]:
"""
df_restaurant contient les colonnes suivantes:
    - name
    - city
    
df_categories contient les clonnes suivantes:
    - restaurant_id = categories_id
    
df_avis contient le nombre de review pour un restaurant
    - restaurant_id count
    
info to find
    - state
    - longitude
    - latitude
    - starts
    - attributes
"""
df_business = DataFrame()

,restaurant_id,nom,moyenne_etoiles,ville,zone,ferme
0,lCwqJWMxvIUQt1Re_tDn4w,Denny's,2.5,Las Vegas,89110,0
1,pd0v6sOqpLhFJ7mkpIaixw,Ike's Love & Sandwiches,4.0,Phoenix,85004,0
2,0vhi__HtC2L4-vScgDFdFw,Midori Japanese Cafe,3.5,Calgary,T2T,0
3,t65yfB9v9fqlhAkLnnUXdg,Pho U,3.5,Toronto,M5A,0
4,i7_JPit-2kAbtRTLkic2jA,John & Sons Oyster House,4.0,Toronto,M5H,0
...,...,...,...,...,...,...
34263,cjZfgcQwA6KmQ_ANWKN2aw,Bruegger's Bagels,3.5,McMurray,15317,1
34264,Hq2edcOTjse7wjK2CwBijQ,Bistro Pointe-Claire,3.5,Pointe-Claire,H9S,1
34265,7KlpgRjjAmVabPzxcExs0g,Taco Mex,4.0,Phoenix,85051,1
34266,0fY-zYyP2fDmp2YXFsuNTg,Gotham Provisions Company,4.0,Sun Prairie,53590,1
34267,cfrN6-lQC-dzjBtNBjefpQ,Rusty Nail Banquet Hall,2.5,Kent,44240,1

In [6]:
df_business

  nom
0   a
1   b
2   c
3   d